spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true



logging:
  level:
    com.gjleon: debug
    net.ttddyy.dsproxy.listener: debug
server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:root}
  password: ${LOCAL_PASSWORD:root}